/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apps;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author FBS
 */
public class pengajuan extends javax.swing.JFrame {
    private DefaultTableModel data;
    Connection conn;
    Statement stm;
    ResultSet rs;
    PreparedStatement pst = null;
    apps.session session = new apps.session();
    
    /**
     * Creates new form pengajuan
     */
    public pengajuan() {
        initComponents();
        kosong();
        tabel();
        kode();
        block();
        ImageIcon img = new ImageIcon("src/focon/logo.png");
        this.setIconImage(img.getImage());
        initUI();
        idwarga.setVisible(false);
        nawar.setText("" + session.getU_username());
        nik.setText("" + session.getU_nik());
        idwarga.setText("" + session.getU_id_warga());
    }
    
    private void initUI(){ 
        getContentPane().setBackground(new Color(245, 245, 245));
        
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();
        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
    }
    
    protected void block(){
    idpengajuan.setEnabled(false);
    status.setEnabled(false);
    keluaran.setEnabled(false);
    tanggal.setEnabled(false);
    nik.setEnabled(false);
    nawar.setEnabled(false);
    }

     protected void kosong(){
        save.setEnabled(true);
        kategori.setSelectedItem(0);
        masukan.setText("");
        keluaran.setText("");
        status.setText("");
        tanggal.setText("");
        idwarga.setText("");
    }
     
    public void kode() {
        try {
        
            String sql = "SELECT * FROM pengajuan ORDER by id desc";
            java.sql.Statement stat = conn.createStatement();
            ResultSet r = stat.executeQuery(sql);

            if (r.next()) {
                String nofak = r.getString("id").substring(1);
                String AN = "" + (Integer.parseInt(nofak) + 1);
                String Nol = "";

                if (AN.length() == 1) {
                    Nol = "000";
                } else if (AN.length() == 2) {
                    Nol = "00";
                } else if (AN.length() == 3) {
                    Nol = "0";
                } else if (AN.length() == 4) {
                    Nol = "";
                }

               idpengajuan.setText("P" + Nol + AN);
            } else {
               idpengajuan.setText("P0001");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }  
    
     private boolean checkIfAlreadySubmittedToday() throws SQLException {
        String today = new SimpleDateFormat("yyyy-MM-dd").format(new Date(System.currentTimeMillis()));

        String checkQuery = "SELECT COUNT(*) AS count FROM pengajuan WHERE id_warga = ? AND tanggal_approve = ?";

        try (PreparedStatement checkStat = conn.prepareStatement(checkQuery)) {
            checkStat.setString(1, idwarga.getText());
            checkStat.setString(2, today);

            try (ResultSet resultSet = checkStat.executeQuery()) {
                if (resultSet.next()) {
                    int count = resultSet.getInt("count");
                    return count > 0;
                }
            }
        }

        return false;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idpengajuan = new javax.swing.JTextField();
        kategori = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        masukan = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        keluaran = new javax.swing.JTextArea();
        save = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tanggal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        idwarga = new javax.swing.JTextField();
        nik = new javax.swing.JTextField();
        nawar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(950, 475));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 475));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(idpengajuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 70, 30));

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KATEGORI MASUKAN", "KATEGORI 1", "KATEGORI 2", "KATEGORI 3" }));
        jPanel1.add(kategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 410, 30));

        masukan.setColumns(20);
        masukan.setRows(5);
        masukan.setText("\n");
        jScrollPane1.setViewportView(masukan);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 410, 40));

        keluaran.setColumns(20);
        keluaran.setRows(5);
        jScrollPane2.setViewportView(keluaran);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 410, 40));

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/focon/save.png"))); // NOI18N
        save.setText("S I M P A N");
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 240, 40));

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/focon/refresh.png"))); // NOI18N
        cancel.setText("B A T A L");
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 240, 40));

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabel);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 880, 100));

        jLabel3.setText("ID / NAMA LENGKAP");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, 30));

        jLabel4.setText("KATEGORI");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, 30));

        jLabel5.setText("STATUS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, 30));

        jLabel6.setText("HASIL");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 30));
        jPanel1.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 410, 30));

        jLabel7.setText("MASUKAN");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/focon/close.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));
        jPanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 410, 30));

        jLabel2.setText("TANGGAL DIRESPON");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 30));
        jPanel1.add(idwarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 50, 30));
        jPanel1.add(nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 90, 30));
        jPanel1.add(nawar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/focon/MENU KELUHAN.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new apps. menu_warga().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
         try {
            String sql = "INSERT INTO pengajuan "
                    + "(id, "
                    + "id_warga, "
                    + "nama_warga, "
                    + "kategori, "
                    + "masukan, "
                    + "status, "
                    + "tanggal_approve, "
                    + "tanggal_feedback, "
                    + "keluaran) "
                    + "VALUES (?,?,?,?,?,?,?,?,?)";

            // Pastikan koneksi database (conn) sudah dibuka sebelumnya

            try (PreparedStatement stat = conn.prepareStatement(sql)) {
                stat.setString(1, idpengajuan.getText());
                stat.setString(2, idwarga.getText());
                stat.setString(3, nawar.getText());
                stat.setString(4, kategori.getSelectedItem().toString());
                stat.setString(5, masukan.getText());
                stat.setString(6, "SEDANG DIPROSES");

                // Menggunakan java.util.Date untuk mendapatkan tanggal hari ini
                Date today = new Date(System.currentTimeMillis());
                // Menggunakan java.sql.Date untuk mengubah ke format yang sesuai dengan database
                stat.setDate(7, new java.sql.Date(today.getTime()));
                stat.setDate(8, new java.sql.Date(today.getTime()));

                stat.setString(9, "-");

                // Memeriksa apakah warga sudah melakukan pengajuan hari ini
                if (checkIfAlreadySubmittedToday()) {
                    JOptionPane.showMessageDialog(null, "Maaf, Anda hanya dapat melakukan pengajuan satu kali dalam sehari.");
                } else {
                    int rowsAffected = stat.executeUpdate();
                    if (rowsAffected > 0) {
                        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                        kosong();
                        idpengajuan.requestFocus();
                        tabel();
                        kode();
                    } else {
                        JOptionPane.showMessageDialog(null, "Tidak ada baris yang terpengaruh");
                    }
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data gagal disimpan: " + e.getMessage());
            tabel();
        }
    }//GEN-LAST:event_saveActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        tabel();
        kode();
        kosong();
    }//GEN-LAST:event_cancelActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
        save.setEnabled(false);
        masukan.setEnabled(false);
        kategori.setEnabled(false);
        int baris = tabel.getSelectedRow();
        idpengajuan.setText(tabel.getModel().getValueAt(baris, 0).toString());
        nawar.setText(tabel.getModel().getValueAt(baris, 2).toString());
        masukan.setText(tabel.getModel().getValueAt(baris, 4).toString());
        status.setText(tabel.getModel().getValueAt(baris, 3).toString());
        tanggal.setText(tabel.getModel().getValueAt(baris, 1).toString());
        keluaran.setText(tabel.getModel().getValueAt(baris, 5).toString());
    }//GEN-LAST:event_tabelMouseClicked
    public Connection setKoneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/projectwarga","root","");
            stm=conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal :" +e);
        }
       return conn; 
    }

    public void tabel(){
        Object header[]={"ID PERMOHONAN","TANGGAL RESPON","NAMA WARGA","STATUS","MASUKAN","KETERANGAN"};
        DefaultTableModel data=new DefaultTableModel(null,header);
        tabel.setModel(data);
        setKoneksi();
        String sql = 
             "SELECT DISTINCT\n" +
             "a.id_approval,\n" +
             "a.id_pengajuan,\n" +
             "a.id_approv,\n" +
             "a.nama_approv,\n" +
             "a.tanggal,\n" +
             "a.nama_warga,\n" +
             "a.status,\n" +
             "a.masukan,\n" +
             "f.feedback\n" +
             "FROM approval a\n" +
             "LEFT JOIN feedback f ON f.id_pengajuan = a.id_pengajuan\n" +
             "WHERE a.nama_warga = ?;";
        try {
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
            preparedStatement.setString(1, session.getU_username());  
            ResultSet rs = preparedStatement.executeQuery();
            while (rs.next())
            {
                String kolom1 = rs.getString("id_pengajuan");
                String kolom2 = rs.getString("tanggal");
                String kolom3 = rs.getString("nama_warga");
                String kolom4 = rs.getString("status");
                String kolom5 = rs.getString("masukan");
                String kolom6 = rs.getString("feedback");

                String kolom[]={kolom1,kolom2,kolom3,kolom4,kolom5,kolom6};
                data.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengajuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengajuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengajuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengajuan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengajuan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField idpengajuan;
    private javax.swing.JTextField idwarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JTextArea keluaran;
    private javax.swing.JTextArea masukan;
    private javax.swing.JTextField nawar;
    private javax.swing.JTextField nik;
    private javax.swing.JButton save;
    private javax.swing.JTextField status;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField tanggal;
    // End of variables declaration//GEN-END:variables
}
