/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apps;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsEnvironment;
import java.awt.Point;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author FBS
 */
public class regiswarga extends javax.swing.JFrame {
    private DefaultTableModel data;
    Connection conn;
    Statement stm;
    ResultSet rs;
    /**
     * Creates new form regiswarga
     */
    public regiswarga() {
        initComponents();
        kosong();
        tabel();
        kode();
        block();
        ImageIcon img = new ImageIcon("src/focon/logo.png");
        this.setIconImage(img.getImage());
        initUI();
    }

    private void initUI(){ 
        getContentPane().setBackground(new Color(245, 245, 245));
        
        Dimension windowSize = getSize();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        Point centerPoint = ge.getCenterPoint();
        int dx = centerPoint.x - windowSize.width / 2;
        int dy = centerPoint.y - windowSize.height / 2;    
        setLocation(dx, dy);
    }
    
    protected void block(){
        id.setEnabled(false);
    }

    protected void kosong(){
        save.setEnabled(true);
        edit.setEnabled(false);
        nama.setText("");
        jk.setSelectedItem(0);
        usia.setText("");
        nohp.setText("");
        nik.setText("");
        kk.setText("");
        alamat.setText("");
    }
     
    public void kode() {
        try {
        
            String sql = "SELECT * FROM warga ORDER by id_warga desc";
            java.sql.Statement stat = conn.createStatement();
            ResultSet r = stat.executeQuery(sql);

            if (r.next()) {
                String nofak = r.getString("id_warga").substring(1);
                String AN = "" + (Integer.parseInt(nofak) + 1);
                String Nol = "";

                if (AN.length() == 1) {
                    Nol = "000";
                } else if (AN.length() == 2) {
                    Nol = "00";
                } else if (AN.length() == 3) {
                    Nol = "0";
                } else if (AN.length() == 4) {
                    Nol = "";
                }

               id.setText("W" + Nol + AN);
            } else {
               id.setText("W0001");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        cancel = new javax.swing.JButton();
        save = new javax.swing.JButton();
        jk = new javax.swing.JComboBox<>();
        nama = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        usia = new javax.swing.JTextField();
        nik = new javax.swing.JTextField();
        kk = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamat = new javax.swing.JTextArea();
        nohp = new javax.swing.JTextField();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        cari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTER WARGA");
        setUndecorated(true);
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(950, 475));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 475));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 850, 130));

        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/focon/refresh.png"))); // NOI18N
        cancel.setText("B A T A L");
        cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 230, 30));

        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/focon/save.png"))); // NOI18N
        save.setText("S I M P A N");
        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 230, 30));

        jk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JENIS KELAMIN", "LAKI-LAKI", "PEREMPUAN" }));
        jPanel1.add(jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 180, 30));
        jPanel1.add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 240, 40));

        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 90, 40));
        jPanel1.add(usia, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 160, 30));
        jPanel1.add(nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 180, 30));
        jPanel1.add(kk, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 160, 30));

        alamat.setColumns(20);
        alamat.setRows(5);
        jScrollPane2.setViewportView(alamat);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 350, 50));
        jPanel1.add(nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 350, 30));

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/focon/edit.png"))); // NOI18N
        edit.setText("E D I T");
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        jPanel1.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 120, 230, 30));

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/focon/delete.png"))); // NOI18N
        delete.setText("H A P U S");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 170, 230, 30));

        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariKeyPressed(evt);
            }
        });
        jPanel1.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 850, 30));

        jLabel3.setText("ID / NAMA WARGA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, 30));

        jLabel4.setText("JENIS KELAMIN / USIA");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, 30));

        jLabel5.setText("NO TELPN / WA");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 30));

        jLabel6.setText("NIK / KK");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 30));

        jLabel7.setText("ALAMAT LENGKAP");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/focon/close.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/focon/MASTER WARGA.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try {
            String sql ="UPDATE warga SET nama_warga = '"+nama.getText()
                    +"',jenis_kelamin ='"+jk.getSelectedItem()
                    +"',usia ='"+usia.getText()
                    +"',nohp ='"+nohp.getText()
                    +"',nik ='"+nik.getText()
                    +"',kk ='"+kk.getText()
                    +"',alamat ='"+alamat.getText()
                    +"' WHERE id_warga = '"+id.getText()+"'";
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/projectwarga","root","");
            stm=conn.createStatement();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e.getMessage());
        }
        tabel();
    }//GEN-LAST:event_editActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
    String wargaSql = "INSERT INTO warga "
                 + "(id_warga, nama_warga, jenis_kelamin, usia, nohp, nik, kk, alamat) "
                 + "VALUES (?,?,?,?,?,?,?,?)";
    String loginSql = "INSERT INTO login "
                 + "(id, nama, username,password, alamat, usia, jenis_kelamin, nohp, nik, kk,id_session, id_warga) "
                 + "VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";

    try {
        PreparedStatement wargaStat = conn.prepareStatement(wargaSql);
        wargaStat.setString(1, id.getText());
        wargaStat.setString(2, nama.getText());
        wargaStat.setString(3, jk.getSelectedItem().toString());
        wargaStat.setString(4, usia.getText());
        wargaStat.setString(5, nohp.getText());
        wargaStat.setString(6, nik.getText());
        wargaStat.setString(7, kk.getText());
        wargaStat.setString(8, alamat.getText());

        PreparedStatement loginStat = conn.prepareStatement(loginSql);
        loginStat.setString(1, id.getText());
        loginStat.setString(2, nama.getText());
        loginStat.setString(3, nama.getText());
        loginStat.setString(4, "12345");
        loginStat.setString(5, alamat.getText());
        loginStat.setString(6, usia.getText());
        loginStat.setString(7, jk.getSelectedItem().toString());
        loginStat.setString(8, nohp.getText());
        loginStat.setString(9, nik.getText());
        loginStat.setString(10, kk.getText());
        loginStat.setString(11, "3");
        loginStat.setString(12, id.getText());

        conn.setAutoCommit(false); // Disable auto-commit to ensure both inserts are successful

        wargaStat.executeUpdate();
        loginStat.executeUpdate();

        conn.commit(); // Commit the changes to both tables

        JOptionPane.showMessageDialog(null, "Data akan disimpan");
        kosong();
        id.requestFocus();
        tabel();
    } catch (SQLException e) {
        try {
            conn.rollback(); // Rollback changes if an error occurs
        } catch (SQLException rollbackException) {
            // Handle rollback exception
        }
        JOptionPane.showMessageDialog(null, "Data gagal disimpan" + e);
        tabel();
    } finally {
        try {
            conn.setAutoCommit(true); // Re-enable auto-commit
        } catch (SQLException autoCommitException) {
            // Handle auto-commit exception
        }
    }
    }//GEN-LAST:event_saveActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Hapus data ini?","Konfirmasi",JOptionPane.YES_NO_OPTION);
        if (ok==0){
            String sql = "delete from warga where nama_warga ='"+nama.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data akan di hapus dari sistem?");
                kosong();
                id.requestFocus();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
            }
            tabel();
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        kosong();
        tabel();
        kode();
    }//GEN-LAST:event_cancelActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
         save.setEnabled(false);
        edit.setEnabled(true);
        int baris = tabel.getSelectedRow();
        id.setText(tabel.getModel().getValueAt(baris, 0).toString());
        nama.setText(tabel.getModel().getValueAt(baris, 1).toString());
        jk.setSelectedItem(tabel.getModel().getValueAt(baris, 2));
        usia.setText(tabel.getModel().getValueAt(baris, 3).toString());
        nohp.setText(tabel.getModel().getValueAt(baris, 4).toString());
        nik.setText(tabel.getModel().getValueAt(baris, 5).toString());
        kk.setText(tabel.getModel().getValueAt(baris, 6).toString());
        alamat.setText(tabel.getModel().getValueAt(baris, 7).toString());
    }//GEN-LAST:event_tabelMouseClicked

    private void cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyPressed
        // TODO add your handling code here:
         Object header[]={"ID WARGA","NAMA","JENIS KELAMIN","USIA","NO HP","NIK","KK","ALAMAT"};
        DefaultTableModel data=new DefaultTableModel(null,header);
        tabel.setModel(data);

        setKoneksi();
        String sql="Select * from warga where id_warga like '%" 
                + cari.getText() + "%'" +"or nama_warga like '%" 
                + cari.getText()+"%'"+ "%'" +"or nik like '%" 
                + cari.getText()+"%'"+ "%'" +"or kk like '%" 
                + cari.getText()+"%'";

        try {
            ResultSet rs=stm.executeQuery(sql);
            while (rs.next())
            {
                String kolom1=rs.getString("id_warga");
                String kolom2=rs.getString("nama_warga");
                String kolom3=rs.getString("jenis_kelamin");
                String kolom4=rs.getString("usia");
                String kolom5=rs.getString("nohp");
                String kolom6=rs.getString("nik");
                String kolom7=rs.getString("kk");
                String kolom8=rs.getString("alamat");

                String kolom[]={kolom1,kolom2,kolom3,kolom4,kolom5,kolom6,kolom7,kolom8};
                data.addRow(kolom);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_cariKeyPressed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        new apps. menu_petugas().setVisible(true);
    }//GEN-LAST:event_jLabel8MouseClicked
 public Connection setKoneksi(){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/projectwarga","root","");
            stm=conn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Koneksi Gagal :" +e);
        }
       return conn; 
    }

public void tabel(){
        Object header[]={"ID WARGA","NAMA","JENIS KELAMIN","USIA","NO HP","NIK","KK","ALAMAT"};
        DefaultTableModel data=new DefaultTableModel(null,header);
        tabel.setModel(data);
        setKoneksi();
        String sql="SELECT * FROM warga";
        try {
            ResultSet rs=stm.executeQuery(sql);
            while (rs.next())
            {
              String kolom1=rs.getString("id_warga");
                String kolom2=rs.getString("nama_warga");
                String kolom3=rs.getString("jenis_kelamin");
                String kolom4=rs.getString("usia");
                String kolom5=rs.getString("nohp");
                String kolom6=rs.getString("nik");
                String kolom7=rs.getString("kk");
                String kolom8=rs.getString("alamat");

                String kolom[]={kolom1,kolom2,kolom3,kolom4,kolom5,kolom6,kolom7,kolom8};
                data.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(regiswarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(regiswarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(regiswarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(regiswarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new regiswarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamat;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField cari;
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jk;
    private javax.swing.JTextField kk;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField nohp;
    private javax.swing.JButton save;
    private javax.swing.JTable tabel;
    private javax.swing.JTextField usia;
    // End of variables declaration//GEN-END:variables
}
